feat: left panel
quibble-dev/Quibble pull request #45
Opened 2024-11-18 17:13 UTC by daaniissh

left panel

2024-11-18 17:18 UTC, moonlitgrace requested changes
@daaniissh i told you like thousand times to make a PR for whole homepage, not just leftpanel or rightpanel.

ps: consider these things next time.

2024-11-18 17:18 UTC, moonlitgrace commented on backend/.gitignore
> +/backend/.env.example
what is your point on this?

2024-11-18 17:18 UTC, moonlitgrace commented on frontend/src/lib/components/Icons/AboutIcon.svelte
seems like you havent updated your fork/local repo... i changed many stuff
ps: we're using an icon lib

2024-11-18 17:18 UTC, moonlitgrace commented on frontend/src/lib/components/User/UserListItem.svelte
> +	import StarFill from '$lib/components/icons/StarFill.svelte';
imports must be on top

2024-11-20 08:03 UTC, moonlitgrace requested changes
this branch is still not updated with upstream.

and please write tailwind classes a bit more carefully, wtf is `w-ful` and why do we need `cursor-pointer`? tailwind is already ugly, don't make it any worse.

running prettier could help.

2024-11-20 08:03 UTC, moonlitgrace commented on frontend/src/routes/+layout.svelte
> +	<RightPanel/>
right panel? what that component does?

2024-11-20 08:07 UTC, daaniissh commented on frontend/src/lib/components/header.svelte
> +				<img draggable="false" alt="moonlitgrace" src="https://i.pinimg.com/736x/ed/ee/a3/edeea3f5e941c09ab9542148aea64de4.jpg" />
sorry

2024-11-20 08:07 UTC, daaniissh commented on frontend/src/lib/utils/formatNumber.ts
ok

2024-11-20 08:12 UTC, moonlitgrace commented on frontend/src/lib/components/RightPanel/rightPanel.svelte
> +<div class="fixed right-0 h-screen w-80">
not `fixed`, make a wrapper for right panel.
well check how reddit is doing this.

2024-11-20 08:13 UTC, daaniissh commented on frontend/src/lib/components/Icons/AboutIcon.svelte
sorry , i forget that, i mean i didn't installed that package ,

2024-11-20 08:28 UTC, daaniissh commented on frontend/src/lib/components/Icons/AboutIcon.svelte
not similar

2024-11-20 08:28 UTC, daaniissh commented on frontend/src/lib/components/Icons/HelpIcon.svelte
done

2024-11-22 12:37 UTC, moonlitgrace approved these changes
LGTM! good work @daaniissh

2024-11-22 12:37 UTC, merged